////////////////////////////////////////////////////////////////////////////////
///                                                                          ///
///  ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░ ░▒▓██████▓▒░  ///
/// ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ///
/// ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░        ///
/// ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓██████▓▒░░▒▓█▓▒░      ░▒▓█▓▒░        ///
/// ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░        ///
/// ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ///
///  ░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░ ░▒▓██████▓▒░  ///
///    ░▒▓█▓▒░                                                               ///
///     ░▒▓██▓▒░                                                             ///
///                                                                          ///
///   * QUIX LANG COMPILER - The official compiler for the Quix language.    ///
///   * Copyright (C) 2024 Wesley C. Jones                                   ///
///                                                                          ///
///   The QUIX Compiler Suite is free software; you can redistribute it or   ///
///   modify it under the terms of the GNU Lesser General Public             ///
///   License as published by the Free Software Foundation; either           ///
///   version 2.1 of the License, or (at your option) any later version.     ///
///                                                                          ///
///   The QUIX Compiler Suite is distributed in the hope that it will be     ///
///   useful, but WITHOUT ANY WARRANTY; without even the implied warranty of ///
///   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      ///
///   Lesser General Public License for more details.                        ///
///                                                                          ///
///   You should have received a copy of the GNU Lesser General Public       ///
///   License along with the QUIX Compiler Suite; if not, see                ///
///   <https://www.gnu.org/licenses/>.                                       ///
///                                                                          ///
////////////////////////////////////////////////////////////////////////////////

#define QUIXCC_INTERNAL

#include <LibMacro.h>
#include <core/Logger.h>
#include <lexer/Lex.h>
#include <preprocessor/Preprocessor.h>

static std::set<std::string> spdx_licenses = {
    "0bsd",
    "aal",
    "abstyles",
    "adacore-doc",
    "adobe-2006",
    "adobe-glyph",
    "adobe-utopia",
    "adsl",
    "afl-1.1",
    "afl-1.2",
    "afl-2.0",
    "afl-2.1",
    "afl-3.0",
    "afmparse",
    "agpl-1.0",
    "agpl-1.0-only",
    "agpl-1.0-or-later",
    "agpl-3.0",
    "agpl-3.0-only",
    "agpl-3.0-or-later",
    "aladdin",
    "amdplpa",
    "aml",
    "ampas",
    "antlr-pd",
    "antlr-pd-fallback",
    "apache-1.0",
    "apache-1.1",
    "apache-2.0",
    "apafml",
    "apl-1.0",
    "app-s2p",
    "apsl-1.0",
    "apsl-1.1",
    "apsl-1.2",
    "apsl-2.0",
    "arphic-1999",
    "artistic-1.0",
    "artistic-1.0-cl8",
    "artistic-1.0-perl",
    "artistic-2.0",
    "aswf-digital-assets-1.0",
    "aswf-digital-assets-1.1",
    "baekmuk",
    "bahyph",
    "barr",
    "beerware",
    "bitstream-charter",
    "bitstream-vera",
    "bittorrent-1.0",
    "bittorrent-1.1",
    "blessing",
    "blueoak-1.0.0",
    "boehm-gc",
    "borceux",
    "brian-gladman-3-clause",
    "bsd-1-clause",
    "bsd-2-clause",
    "bsd-2-clause-freebsd",
    "bsd-2-clause-netbsd",
    "bsd-2-clause-patent",
    "bsd-2-clause-views",
    "bsd-3-clause",
    "bsd-3-clause-attribution",
    "bsd-3-clause-clear",
    "bsd-3-clause-flex",
    "bsd-3-clause-hp",
    "bsd-3-clause-lbnl",
    "bsd-3-clause-modification",
    "bsd-3-clause-no-military-license",
    "bsd-3-clause-no-nuclear-license",
    "bsd-3-clause-no-nuclear-license-2014",
    "bsd-3-clause-no-nuclear-warranty",
    "bsd-3-clause-open-mpi",
    "bsd-3-clause-sun",
    "bsd-4-clause",
    "bsd-4-clause-shortened",
    "bsd-4-clause-uc",
    "bsd-4.3reno",
    "bsd-4.3tahoe",
    "bsd-advertising-acknowledgement",
    "bsd-attribution-hpnd-disclaimer",
    "bsd-inferno-nettverk",
    "bsd-protection",
    "bsd-source-code",
    "bsd-systemics",
    "bsl-1.0",
    "busl-1.1",
    "bzip2-1.0.5",
    "bzip2-1.0.6",
    "c-uda-1.0",
    "cal-1.0",
    "cal-1.0-combined-work-exception",
    "caldera",
    "catosl-1.1",
    "cc-by-1.0",
    "cc-by-2.0",
    "cc-by-2.5",
    "cc-by-2.5-au",
    "cc-by-3.0",
    "cc-by-3.0-at",
    "cc-by-3.0-de",
    "cc-by-3.0-igo",
    "cc-by-3.0-nl",
    "cc-by-3.0-us",
    "cc-by-4.0",
    "cc-by-nc-1.0",
    "cc-by-nc-2.0",
    "cc-by-nc-2.5",
    "cc-by-nc-3.0",
    "cc-by-nc-3.0-de",
    "cc-by-nc-4.0",
    "cc-by-nc-nd-1.0",
    "cc-by-nc-nd-2.0",
    "cc-by-nc-nd-2.5",
    "cc-by-nc-nd-3.0",
    "cc-by-nc-nd-3.0-de",
    "cc-by-nc-nd-3.0-igo",
    "cc-by-nc-nd-4.0",
    "cc-by-nc-sa-1.0",
    "cc-by-nc-sa-2.0",
    "cc-by-nc-sa-2.0-de",
    "cc-by-nc-sa-2.0-fr",
    "cc-by-nc-sa-2.0-uk",
    "cc-by-nc-sa-2.5",
    "cc-by-nc-sa-3.0",
    "cc-by-nc-sa-3.0-de",
    "cc-by-nc-sa-3.0-igo",
    "cc-by-nc-sa-4.0",
    "cc-by-nd-1.0",
    "cc-by-nd-2.0",
    "cc-by-nd-2.5",
    "cc-by-nd-3.0",
    "cc-by-nd-3.0-de",
    "cc-by-nd-4.0",
    "cc-by-sa-1.0",
    "cc-by-sa-2.0",
    "cc-by-sa-2.0-uk",
    "cc-by-sa-2.1-jp",
    "cc-by-sa-2.5",
    "cc-by-sa-3.0",
    "cc-by-sa-3.0-at",
    "cc-by-sa-3.0-de",
    "cc-by-sa-3.0-igo",
    "cc-by-sa-4.0",
    "cc-pddc",
    "cc0-1.0",
    "cddl-1.0",
    "cddl-1.1",
    "cdl-1.0",
    "cdla-permissive-1.0",
    "cdla-permissive-2.0",
    "cdla-sharing-1.0",
    "cecill-1.0",
    "cecill-1.1",
    "cecill-2.0",
    "cecill-2.1",
    "cecill-b",
    "cecill-c",
    "cern-ohl-1.1",
    "cern-ohl-1.2",
    "cern-ohl-p-2.0",
    "cern-ohl-s-2.0",
    "cern-ohl-w-2.0",
    "cfitsio",
    "check-cvs",
    "checkmk",
    "clartistic",
    "clips",
    "cmu-mach",
    "cnri-jython",
    "cnri-python",
    "cnri-python-gpl-compatible",
    "coil-1.0",
    "community-spec-1.0",
    "condor-1.1",
    "copyleft-next-0.3.0",
    "copyleft-next-0.3.1",
    "cornell-lossless-jpeg",
    "cpal-1.0",
    "cpl-1.0",
    "cpol-1.02",
    "cronyx",
    "crossword",
    "crystalstacker",
    "cua-opl-1.0",
    "cube",
    "curl",
    "d-fsl-1.0",
    "diffmark",
    "dl-de-by-2.0",
    "dl-de-zero-2.0",
    "doc",
    "dotseqn",
    "drl-1.0",
    "dsdp",
    "dtoa",
    "dvipdfm",
    "ecl-1.0",
    "ecl-2.0",
    "ecos-2.0",
    "efl-1.0",
    "efl-2.0",
    "egenix",
    "elastic-2.0",
    "entessa",
    "epics",
    "epl-1.0",
    "epl-2.0",
    "erlpl-1.1",
    "etalab-2.0",
    "eudatagrid",
    "eupl-1.0",
    "eupl-1.1",
    "eupl-1.2",
    "eurosym",
    "fair",
    "fbm",
    "fdk-aac",
    "ferguson-twofish",
    "frameworx-1.0",
    "freebsd-doc",
    "freeimage",
    "fsfap",
    "fsful",
    "fsfullr",
    "fsfullrwd",
    "ftl",
    "furuseth",
    "fwlw",
    "gd",
    "gfdl-1.1",
    "gfdl-1.1-invariants-only",
    "gfdl-1.1-invariants-or-later",
    "gfdl-1.1-no-invariants-only",
    "gfdl-1.1-no-invariants-or-later",
    "gfdl-1.1-only",
    "gfdl-1.1-or-later",
    "gfdl-1.2",
    "gfdl-1.2-invariants-only",
    "gfdl-1.2-invariants-or-later",
    "gfdl-1.2-no-invariants-only",
    "gfdl-1.2-no-invariants-or-later",
    "gfdl-1.2-only",
    "gfdl-1.2-or-later",
    "gfdl-1.3",
    "gfdl-1.3-invariants-only",
    "gfdl-1.3-invariants-or-later",
    "gfdl-1.3-no-invariants-only",
    "gfdl-1.3-no-invariants-or-later",
    "gfdl-1.3-only",
    "gfdl-1.3-or-later",
    "giftware",
    "gl2ps",
    "glide",
    "glulxe",
    "glwtpl",
    "gnuplot",
    "gpl-1.0",
    "gpl-1.0+",
    "gpl-1.0-only",
    "gpl-1.0-or-later",
    "gpl-2.0",
    "gpl-2.0+",
    "gpl-2.0-only",
    "gpl-2.0-or-later",
    "gpl-2.0-with-autoconf-exception",
    "gpl-2.0-with-bison-exception",
    "gpl-2.0-with-classpath-exception",
    "gpl-2.0-with-font-exception",
    "gpl-2.0-with-gcc-exception",
    "gpl-3.0",
    "gpl-3.0+",
    "gpl-3.0-only",
    "gpl-3.0-or-later",
    "gpl-3.0-with-autoconf-exception",
    "gpl-3.0-with-gcc-exception",
    "graphics-gems",
    "gsoap-1.3b",
    "haskellreport",
    "hippocratic-2.1",
    "hp-1986",
    "hp-1989",
    "hpnd",
    "hpnd-dec",
    "hpnd-doc",
    "hpnd-doc-sell",
    "hpnd-export-us",
    "hpnd-export-us-modify",
    "hpnd-markus-kuhn",
    "hpnd-pbmplus",
    "hpnd-sell-regexpr",
    "hpnd-sell-variant",
    "hpnd-sell-variant-mit-disclaimer",
    "hpnd-uc",
    "htmltidy",
    "ibm-pibs",
    "icu",
    "iec-code-components-eula",
    "ijg",
    "ijg-short",
    "imagemagick",
    "imatix",
    "imlib2",
    "info-zip",
    "inner-net-2.0",
    "intel",
    "intel-acpi",
    "interbase-1.0",
    "ipa",
    "ipl-1.0",
    "isc",
    "jam",
    "jasper-2.0",
    "jpl-image",
    "jpnic",
    "json",
    "kastrup",
    "kazlib",
    "knuth-ctan",
    "lal-1.2",
    "lal-1.3",
    "latex2e",
    "latex2e-translated-notice",
    "leptonica",
    "lgpl-2.0",
    "lgpl-2.0+",
    "lgpl-2.0-only",
    "lgpl-2.0-or-later",
    "lgpl-2.1",
    "lgpl-2.1+",
    "lgpl-2.1-only",
    "lgpl-2.1-or-later",
    "lgpl-3.0",
    "lgpl-3.0+",
    "lgpl-3.0-only",
    "lgpl-3.0-or-later",
    "lgpllr",
    "libpng",
    "libpng-2.0",
    "libselinux-1.0",
    "libtiff",
    "libutil-david-nugent",
    "liliq-p-1.1",
    "liliq-r-1.1",
    "liliq-rplus-1.1",
    "linux-man-pages-1-para",
    "linux-man-pages-copyleft",
    "linux-man-pages-copyleft-2-para",
    "linux-man-pages-copyleft-var",
    "linux-openib",
    "loop",
    "lpl-1.0",
    "lpl-1.02",
    "lppl-1.0",
    "lppl-1.1",
    "lppl-1.2",
    "lppl-1.3a",
    "lppl-1.3c",
    "lsof",
    "lucida-bitmap-fonts",
    "lzma-sdk-9.11-to-9.20",
    "lzma-sdk-9.22",
    "magaz",
    "makeindex",
    "martin-birgmeier",
    "mcphee-slideshow",
    "metamail",
    "minpack",
    "miros",
    "mit",
    "mit-0",
    "mit-advertising",
    "mit-cmu",
    "mit-enna",
    "mit-feh",
    "mit-festival",
    "mit-modern-variant",
    "mit-open-group",
    "mit-testregex",
    "mit-wu",
    "mitnfa",
    "mmixware",
    "motosoto",
    "mpeg-ssg",
    "mpi-permissive",
    "mpich2",
    "mpl-1.0",
    "mpl-1.1",
    "mpl-2.0",
    "mpl-2.0-no-copyleft-exception",
    "mplus",
    "ms-lpl",
    "ms-pl",
    "ms-rl",
    "mtll",
    "mulanpsl-1.0",
    "mulanpsl-2.0",
    "multics",
    "mup",
    "naist-2003",
    "nasa-1.3",
    "naumen",
    "nbpl-1.0",
    "ncgl-uk-2.0",
    "ncsa",
    "net-snmp",
    "netcdf",
    "newsletr",
    "ngpl",
    "nicta-1.0",
    "nist-pd",
    "nist-pd-fallback",
    "nist-software",
    "nlod-1.0",
    "nlod-2.0",
    "nlpl",
    "nokia",
    "none",
    "nosl",
    "noweb",
    "npl-1.0",
    "npl-1.1",
    "nposl-3.0",
    "nrl",
    "ntp",
    "ntp-0",
    "nunit",
    "o-uda-1.0",
    "occt-pl",
    "oclc-2.0",
    "odbl-1.0",
    "odc-by-1.0",
    "offis",
    "ofl-1.0",
    "ofl-1.0-no-rfn",
    "ofl-1.0-rfn",
    "ofl-1.1",
    "ofl-1.1-no-rfn",
    "ofl-1.1-rfn",
    "ogc-1.0",
    "ogdl-taiwan-1.0",
    "ogl-canada-2.0",
    "ogl-uk-1.0",
    "ogl-uk-2.0",
    "ogl-uk-3.0",
    "ogtsl",
    "oldap-1.1",
    "oldap-1.2",
    "oldap-1.3",
    "oldap-1.4",
    "oldap-2.0",
    "oldap-2.0.1",
    "oldap-2.1",
    "oldap-2.2",
    "oldap-2.2.1",
    "oldap-2.2.2",
    "oldap-2.3",
    "oldap-2.4",
    "oldap-2.5",
    "oldap-2.6",
    "oldap-2.7",
    "oldap-2.8",
    "olfl-1.3",
    "oml",
    "openpbs-2.3",
    "openssl",
    "opl-1.0",
    "opl-uk-3.0",
    "opubl-1.0",
    "oset-pl-2.1",
    "osl-1.0",
    "osl-1.1",
    "osl-2.0",
    "osl-2.1",
    "osl-3.0",
    "padl",
    "parity-6.0.0",
    "parity-7.0.0",
    "pddl-1.0",
    "php-3.0",
    "php-3.01",
    "plexus",
    "pnmstitch",
    "polyform-noncommercial-1.0.0",
    "polyform-small-business-1.0.0",
    "postgresql",
    "psf-2.0",
    "psfrag",
    "psutils",
    "python-2.0",
    "python-2.0.1",
    "python-ldap",
    "qhull",
    "qpl-1.0",
    "qpl-1.0-inria-2004",
    "rdisc",
    "rhecos-1.1",
    "rpl-1.1",
    "rpl-1.5",
    "rpsl-1.0",
    "rsa-md",
    "rscpl",
    "ruby",
    "sax-pd",
    "saxpath",
    "scea",
    "schemereport",
    "sendmail",
    "sendmail-8.23",
    "sgi-b-1.0",
    "sgi-b-1.1",
    "sgi-b-2.0",
    "sgi-opengl",
    "sgp4",
    "shl-0.5",
    "shl-0.51",
    "simpl-2.0",
    "sissl",
    "sissl-1.2",
    "sl",
    "sleepycat",
    "smlnj",
    "smppl",
    "snia",
    "snprintf",
    "soundex",
    "spencer-86",
    "spencer-94",
    "spencer-99",
    "spl-1.0",
    "ssh-keyscan",
    "ssh-openssh",
    "ssh-short",
    "sspl-1.0",
    "standardml-nj",
    "sugarcrm-1.1.3",
    "sunpro",
    "swl",
    "swrule",
    "symlinks",
    "tapr-ohl-1.0",
    "tcl",
    "tcp-wrappers",
    "termreadkey",
    "tmate",
    "torque-1.1",
    "tosl",
    "tpdl",
    "tpl-1.0",
    "ttwl",
    "ttyp0",
    "tu-berlin-1.0",
    "tu-berlin-2.0",
    "ucar",
    "ucl-1.0",
    "ulem",
    "unicode-dfs-2015",
    "unicode-dfs-2016",
    "unicode-tou",
    "unixcrypt",
    "unlicense",
    "upl-1.0",
    "urt-rle",
    "vim",
    "vostrom",
    "vsl-1.0",
    "w3c",
    "w3c-19980720",
    "w3c-20150513",
    "w3m",
    "watcom-1.0",
    "widget-workshop",
    "wsuipa",
    "wtfpl",
    "wxwindows",
    "x11",
    "x11-distribute-modifications-variant",
    "xdebug-1.03",
    "xerox",
    "xfig",
    "xfree86-1.1",
    "xinetd",
    "xlock",
    "xnet",
    "xpp",
    "xskat",
    "ypl-1.0",
    "ypl-1.1",
    "zed",
    "zeeff",
    "zend-2.0",
    "zimbra-1.3",
    "zimbra-1.4",
    "zlib",
    "zlib-acknowledgement",
    "zpl-1.1",
    "zpl-2.0",
    "zpl-2.1",
};

bool libquixcc::PrepEngine::ParseLicense(const Token &tok,
                                         const std::string &directive,
                                         const std::string &parameter) {
  (void)tok;
  (void)directive;

  auto lexer = clone();
  lexer->set_source(parameter, "<license-macro>");

  Token tok2 = lexer->next();
  if (tok2.type != TT::String) {
    LOG(ERROR) << "Invalid SPDX license identifier: '{}'. All License macros "
                  "must use a valid SPDX license identifier."
               << parameter << tok << std::endl;
    return false;
  }

  std::string lower = tok2.as<std::string>();
  std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);

  // Force coders to choose a SPDX license identifier if they use the macro
  if (!spdx_licenses.contains(lower)) {
    LOG(ERROR) << "Invalid SPDX license identifier: '{}'. All License macros "
                  "must use a valid SPDX license identifier."
               << lower << tok << std::endl;
    return false;
  }

  std::string identifier = "__LICENSE__";
  for (auto &c : std::string(job->m_filename.top())) {
    if (std::isalnum(c))
      identifier += c;
    else
      identifier += '_';
  }

  emit(Token(TT::Keyword, Keyword::Pub));
  emit(Token(TT::Keyword, Keyword::Let));
  emit(Token(TT::Identifier, identifier));
  emit(Token(TT::Punctor, Punctor::Colon));
  emit(Token(TT::Identifier, "string"));
  emit(Token(TT::Operator, Operator::Assign));
  emit(Token(TT::String, lower));
  emit(Token(TT::Punctor, Punctor::Semicolon));

  return true;
}