	.text
	.file	"struct.q"
	.section	.text.main,"ax",@progbits
	.globl	main                            # -- Begin function main
	.p2align	4, 0x90
	.type	main,@function
main:                                   # @main
	.cfi_startproc
# %bb.0:                                # %entry
	jmp	.LBB0_1
.LBB0_1:                                # %end
	retq
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
	.cfi_endproc
                                        # -- End function
	.type	_ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60,@object # @_ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60
	.section	.bss._ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60,"aw",@nobits
	.globl	_ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60
	.p2align	4
_ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60:
	.zero	304
	.size	_ZJ0l4data54t10a5t1i1i2x820a13t5t1i1i5t1i1i3x1217a11p9t3p1b1i1i2x60, 304

	.section	".note.GNU-stack","",@progbits
	.addrsig
