	.text
	.file	"union.q"
	.globl	main
	.p2align	4, 0x90
	.type	main,@function
main:
	.cfi_startproc
	retq
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
	.cfi_endproc

	.type	_ZJ0l2x07u1g1i1d0,@object
	.bss
	.globl	_ZJ0l2x07u1g1i1d0
	.p2align	3
_ZJ0l2x07u1g1i1d0:
	.zero	8
	.size	_ZJ0l2x07u1g1i1d0, 8

	.type	_ZJ0l2x17u1e1l1q0,@object
	.globl	_ZJ0l2x17u1e1l1q0
	.p2align	3
_ZJ0l2x17u1e1l1q0:
	.zero	12
	.size	_ZJ0l2x17u1e1l1q0, 12

	.section	".note.GNU-stack","",@progbits
